# Site settings
title: Kailash A. Hambarde
name: Kailash A. Hambarde
position: Researcher
affiliation: Instituto de Telecomunicações & University of Beira Interior
email: kailash.hambarde@ubi.pt
description: >-
  My research focuses on computer vision, person re-identification, and deep learning.

baseurl: ""
url: "https://kailashhambarde.github.io"

# Social links
twitter_username: kailas_srt
github_username: kailashhambarde
google_scholar: W0gfv-UAAAAJ
google_analytics: G-MFWSBLRKG0
it_profile: "https://www.it.pt/Members/Index/40083"
linkedin_username: "kailash-a-hambarde-1978b4106"
phone: "+351 932518298"
cienciavitae: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact
